package how.to.soundp.bean

/**
 *author : jichang
 *time   : 2017/06/09
 *desc   :
 *version: 1.0
 */

data class url(val show_link: String,
               val down_type: Long,
               val original: Long,
               val free: Long,
               val replay_gain: String,
               val song_file_id: Long,
               val file_size: Long,
               val file_extension: String,
               val file_duration: Long,
               val can_see: Long,
               val can_load: Boolean,
               val preload: Long,
               val file_bitrate: Long,
               val file_link: String,
               val is_udition_url: Long,
               val hash: String)

data class songurl(val url: List<url>)
data class artist_list(val avatar_mini: String,
                       val avatar_s300: String,
                       val ting_uid: String,
                       val del_status: String,
                       val avatar_s500: String,
                       val artist_name: String,
                       val avatar_small: String,
                       val avatar_s180: String,
                       val artist_id: String)

data class songinfo(val resource_type_ext: String,
                    val resource_type: String,
                    val del_status: String,
                    val collect_num: Long,
                    val hot: String,
                    val sound_effect: String,
                    val title: String,
                    val language: String,
                    val play_type: Long,
                    val country: String,
                    val biaoshi: String,
                    val bitrate_fee: String,
                    val song_source: String,
                    val is_first_publish: Long,
                    val artist_640_1136: String,
                    val charge: Long,
                    val album_500_500: String,
                    val korean_bb_song: String,
                    val has_mv_mobile: Long,
                    val album_no: String,
                    val is_charge: String,
                    val pic_radio: String,
                    val pic_huge: String,
                    val ting_uid: String,
                    val expire: Long,
                    val pic_singer: String,
                    val compose: String,
                    val toneid: String,
                    val area: String,
                    val original_rate: String,
                    val artist_500_500: String,
                    val multiterminal_copytype: String,
                    val has_mv: Long,
                    val album_title: String,
                    val piao_id: String,
                    val high_rate: String,
                    val album_1000_1000: String,
                    val lrclink: String,
                    val distribution: String,
                    val relate_status: String,
                    val learn: Long,
                    val pic_big: String,
                    val artist: String,
                    val aliasname: String,
                    val artist_list: List<artist_list>,
                    val comment_num: Long,
                    val album_id: String,
                    val share_num: Long,
                    val song_id: String,
                    val artist_480_800: String,
                    val all_rate: String,
                    val author: String,
                    val share_url: String,
                    val all_artist_id: String,
                    val songwriting: String,
                    val publishtime: String,
                    val copy_type: String,
                    val artist_1000_1000: String,
                    val versions: String,
                    val file_duration: String,
                    val artist_id: String,
                    val original: Long,
                    val compress_status: String,
                    val pic_small: String,
                    val pic_premium: String,
                    val bitrate: String,
                    val havehigh: Long)

data class Parent(val songurl: songurl,
                  val error_code: Long,
                  val songinfo: songinfo)